CREATE TABLE `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL,
  `password_hash` varchar(255) NOT NULL,
  `name` varchar(100) NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `companies` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(180) NOT NULL,
  `sector` VARCHAR(120) NULL,
  `phone` VARCHAR(50) NULL,
  `whatsapp` VARCHAR(50) NULL,
  `email` VARCHAR(180) NULL,
  `website` VARCHAR(255) NULL,
  `instagram` VARCHAR(255) NULL,
  `facebook` VARCHAR(255) NULL,
  `linkedin` VARCHAR(255) NULL,
  `address` TEXT NULL,
  `district` VARCHAR(120) NULL,
  `city` VARCHAR(120) DEFAULT 'Konya',
  `source` VARCHAR(100) NULL,
  `notes` TEXT NULL,
  `google_place_id` VARCHAR(255) NULL,
  `enrichment_status` VARCHAR(50) NULL,
  `last_enriched_at` DATETIME NULL,
  `status` ENUM('new', 'contacted', 'replied', 'proposal', 'customer', 'negative') NOT NULL DEFAULT 'new',
  `first_contact_at` DATETIME NULL,
  `last_contact_at` DATETIME NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX (`name`),
  INDEX (`sector`),
  INDEX (`status`),
  INDEX (`city`),
  INDEX (`district`),
  INDEX (`phone`),
  INDEX (`website`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
